services:
    app:
        build: .
        ports:
            - '8777:8000'
        volumes:
            - .:/app
        # PROD
        # command: "uvicorn main:app --host 0.0.0.0 --port 8000"
        # DEV
        command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        # restart: always
        container_name: webp-converter
